Fixes and Support CUDA 11.7 and PyTorch 2.0.1
diningphil/gnn-comparison pull request #40
Opened 2023-08-24 22:11 UTC by SamirMoustafa

# Pull Request: Enhancements and Fixes

## Summary
This pull request includes several key updates and fixes to improve compatibility and clean up the codebase.

## Changes

### Support for CUDA 11.7 and PyTorch 2.0.1
- Upgraded the code to work with CUDA 11.7, enabling more efficient GPU computation.
- Updated dependencies to support PyTorch 2.0.1, ensuring compatibility with the latest version.

### Bug Fixes
- **Fixed None Type Exception**: Addressed an issue where None types would raise an exception in the dataset when they don't exist (`v_outs`, `g_outs`, `e_outs`, `o_outs`).

### Import and Requirement Cleanup
- **Fixed Import Error**: Resolved an import error related to the new version of PyTorch Geometric.
- **Removed Unnecessary Imports**: Cleaned up the code by removing imports that were no longer required.
- **Removed CPU Support Requirements**: Simplified the requirements by removing dependencies that were only needed for CPU support.

## Testing
Please ensure to thoroughly test these changes in your environment to confirm that they do not introduce new issues.

## Conclusion
These updates align our code with the latest technology and remove unnecessary elements, making the code more efficient and maintainable. Please review the changes and let me know if there are any concerns or additional modifications needed.

Thank you!

2023-08-25 07:25 UTC, diningphil requested changes
Dear Samir,

First of all, thank you for your efforts, it is very appreciated.

My main concern is also written in the review: I do not want to abandon the version used originally to run the experiments. People should be able to install the same environment that I used, **and optionally try with newer ones.**

To accept your changes, you should make sure that depending on the CUDA version, different Pytorch and Pytorch Geometric versions are used. This may require **adding options**, rather than changing altogether, the content of the setup script.

Thanks again!
Federico

2023-08-25 07:25 UTC, diningphil commented on README.md
The goal of this library is not to stay up to date with the latest releases but rather to reproduce the results of the paper.

The only way in which the script could change is allowing the use of newer CUDA versions and consequently Pytorch / Pytorch Geometric versions.

So, the existing code should stay the same and, in case the Pytorch version is higher than 1.4.0 (say the most recent one), the logic accepts different CUDA versions that are supported by that version.

2023-08-25 07:25 UTC, diningphil commented on datasets/data.py
If you use the Data object defined in this file, you do not need to specify this. However I think it is still ok to add these checks.

2023-08-25 07:25 UTC, diningphil commented on environment.yml
See my comment on the README.md file. We should support different cuda versions, because the user that wants to reproduce the results of the paper should be able to create an env with Pytorch 1.4.0.

2023-08-25 07:25 UTC, diningphil commented on install.sh
See my comment on README.md

2023-08-25 07:25 UTC, diningphil commented on models/graph_classifiers/ECC.py
This is a problem. Depending on the pytorch geometric version, we should change the import to allow different versions to work.

2023-08-25 14:54 UTC, SamirMoustafa reviewed
Please let me know if you have any other concerns about the pull request.

2023-08-25 14:54 UTC, SamirMoustafa commented on datasets/data.py
Somehow, this was causing a problem.
The message that I received was the following:
`AttributeError: 'GlobalStorage' object has no attribute 'v_outs'`
I think this is due to the fact that recent PyTorch Geometric data classes don't set attributes that have a `None` value [1].

1. `torch_geometric.data.data`: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/data.py#L479

2023-08-25 14:54 UTC, SamirMoustafa commented on models/graph_classifiers/ECC.py
The `ECConv` class is located in `torch_geometric.nn`, even for the old version (1.4.2) of `torch_geometric`.
https://github.com/pyg-team/pytorch_geometric/blob/1.4.2/torch_geometric/nn/conv/__init__.py#L20

2023-08-25 14:54 UTC, SamirMoustafa commented on README.md
I added a rollback to the old version, with some modifications that allow compatibility with the old CUDA and PyTorch versions, including CUDA `11.7.0` and PyTorch `2.0.1`.
The default values were set to PyTorch `2.0.1` and `cpu` in the installation script.

2023-08-25 14:54 UTC, SamirMoustafa commented on environment.yml
I addressed this in the README.md comments as well. The entire `environment.yml` file was removed.

2023-08-25 14:54 UTC, SamirMoustafa commented on install.sh
I replied to this in the README.md comments as well.

2023-08-25 15:08 UTC, diningphil commented on requirements.txt
No need to add copyright here, but if you do please include the University of Pisa

2023-08-25 15:10 UTC, diningphil commented on install.sh
please change to 

Copyright (C)  2020  University of Pisa
Copyright (C)  2023 University of Pisa, University of Vienna

2023-08-25 15:16 UTC, diningphil commented on install.sh
This is also not ok. If pytorch 1.4.0 is used, torch geometric 1.4.2 should be selected.

We should create an if-then-else: if pytorch version is 1.4.0, use old install. If version is > 0 (or simply 2.0.1), use torch geometric 2.3.1

2023-08-25 15:17 UTC, diningphil commented on README.md
```To use cuda it is recommended to install the `cu117` version of pytorch, which is the one we used for our experiments.```

This is not true. 
Please change to "We recommend using the newest versions of Pytorch 2.0.1 and CUDA 11.7 (cu117), which will install Pytorch Geometric 2.3.1. However, the experiments of the paper have been run using Pytorch 1.4.0 and Pytorch Geometric 1.4.2."

2023-08-25 15:20 UTC, diningphil requested changes
Dear Samir,

Thanks again. A few more changes are needed. 

I want to make sure that
- the old installation works as before (see comments) 
- if torch > 2 is installed, then you install other packages like torch geometric 2.3.1
- the copyright should also mention Pisa as first name for 2023 as well

Please see my comments for more details.

2023-08-25 16:24 UTC, SamirMoustafa reviewed
Hi,
I made the requested changes. Please let me know if there are any other changes needed. Thanks for your revision! =)

2023-08-25 16:24 UTC, SamirMoustafa commented on requirements.txt
I removed the entire copyright since this is an open-source package names [😊](smiling-face-with-smiling-eyes)

2023-08-25 16:24 UTC, SamirMoustafa commented on install.sh
Please have a look at the script now, and let me know your opinion.

2023-08-25 16:24 UTC, SamirMoustafa commented on README.md
Sorry for this misleading text. I changed it as you requested.

2023-08-26 08:25 UTC, diningphil requested changes

2023-08-26 08:25 UTC, diningphil commented on install.sh
Dear Samir,

```source install.sh 2.0.1 cu117``` is still installing python 3,7 and torch geometric 1.4.2. There has to be a bug in the installation script.

Could you please test the correct functioning of all cases (1.4.0 with cpu, 2.0.1 with cpu and cu117)? It is sufficient to test that GIN and ECC start training on NCI1.

Many thanks!

2023-08-26 10:24 UTC, SamirMoustafa commented on install.sh
Hi,

I've made minor change to the conditions to address the issue. 
I hope this resolves any problems you were experiencing with `install.sh 2.0.1 cu117`.
Here are the results I get for some versions now:

```
$> ./install.sh          
Python version: 3.10
Installing PyTorch 2.0.1 with CUDA cpu support
Torch Geometric version: 2.3.1
...
$> ./install.sh 1.4.0 cpu
Python version: 3.7
Installing PyTorch 1.4.0 with CUDA cpu support
Torch Geometric version: 1.4.2
...
$> ./install.sh 2.0.1 cpu
Python version: 3.10
Installing PyTorch 2.0.1 with CUDA cpu support
Torch Geometric version: 2.3.1
...
$> ./install.sh 2.0.1 cu117
Python version: 3.10
Installing PyTorch 2.0.1 with CUDA cu117 support
Torch Geometric version: 2.3.1
...
$> ./install.sh 1.4.0 cu92 
Python version: 3.7
Installing PyTorch 1.4.0 with CUDA cu92 support
Torch Geometric version: 1.4.2
...
$> ./install.sh 1.5.0 cu100
Python version: 3.7
Installing PyTorch 1.5.0 with CUDA cu100 support
Torch Geometric version: 1.4.2
...
$> ./install.sh 1.9.0 cu101
Python version: 3.7
Installing PyTorch 1.9.0 with CUDA cu101 support
Torch Geometric version: 1.4.2
..
```

2023-08-26 10:51 UTC, diningphil requested changes

2023-08-26 10:51 UTC, diningphil commented on install.sh
What I meant is, what you print in the script is not necessarily what might be installed, due do dependencies.. did you check that the installed versions are actually consistent throughout the different installations?

2023-08-26 10:51 UTC, diningphil commented on install.sh
For instance:

- If I install the environment with 1.4.0 and cpu, I cannot import torch_geometric from the python interpreter.
- If I choose 2.0.1 and cpu, I get torch 1.13.0+cu116 installed (torch geometric 2.3.1 installed correctly)

Please try to recreate the environments yourself to check this.

2023-08-26 11:33 UTC, SamirMoustafa commented on install.sh
Yes, due to dependencies, it's not straightforward to trace back and ensure that the required versions are exactly the ones that will be installed. That's why, at the beginning of this pull request, I chose to simply update the code to be compatible with the supported CUDA driver and PyTorch version.

Have you tried running the original code with PyTorch 1.14 and either a CPU or CUDA [9/10]? Did the environment install correctly?

2023-08-26 14:22 UTC, diningphil commented on install.sh
As I wrote above, I tried but I cannot import torch geometric, so there is something not working also in that case

2023-08-26 14:40 UTC, diningphil commented on install.sh
Thanks for helping me notice, I will prepare another installer that does not rely on conda to avoid all these issues

2023-08-26 14:55 UTC, SamirMoustafa commented on install.sh
You're welcome! =)
I tried this with `torch_sparse`, and it turns out that the issue isn't limited to whether or not we're using Conda. 
The problem lies in the fact that older versions of `PyG` are not well-maintained to make them compatible with older versions of PyTorch and CUDA.

2023-08-26 14:57 UTC, SamirMoustafa commented on install.sh
I can take on this task since I need this repository to function properly, since I'll be referring to it in future submissions. 
If you have any ideas on how to resolve this issue, I'd be eager to implement the solution as soon as possible and include it in this pull request.

2023-08-26 15:07 UTC, diningphil commented on install.sh
I am already working on it, give me some time and I'll update you when the new installation script is ready.

Then you can remove the install.sh script from the pull request and I will accept the remaining changes.

2023-08-26 15:36 UTC, SamirMoustafa commented on install.sh
okay perfect

2023-08-26 16:08 UTC, diningphil reviewed
Dear Samir,

I created and tested two scripts, one to recreate the original environment and another to create new ones. Please refer to README.md.

I included the University of Vienna in the install.sh file and optimized the imports using Pycharm. I think there is nothing else left to do compared to this pull request.

If you are ok you could test the main branch of gnn-comparison and check that it works as intented for Pytorch 2.0.1 and Geometric 2.3.1.

Thanks again for the help! I did not notice that the installation script was so messed up after these years =).

2023-08-26 18:40 UTC, SamirMoustafa commented
Dr. Errica,

Thank you for the update. The repository is now compatible with PyTorch 2.0.1 and Torch Geometric 2.3.1. I've aligned the files in this pull request with the ones you updated in the original code. Feel free to merge it if you find it appropriate, or you can close the pull request if you prefer.

Thanks again, and have a nice day! [😊](smiling-face-with-smiling-eyes)

2023-08-26 19:15 UTC, closed without merging